# Generated by Django 2.1.5 on 2019-05-25 02:54

import cours.Fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapitre',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='chapitre',
            name='order',
            field=cours.Fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=cours.Fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
