# Generated by Django 2.1.5 on 2019-05-25 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_auto_20190525_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='duree',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
